name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        uses: ./.github/actions/action.yml
        with:
          scope: Dev
          configFile: './.github/file.json'
          secrets: '${{ toJson(secrets) }}'
