on: [push]
jobs:
  deploy_to_dev:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: My first step
        uses: ./.github/actions/json
        with:
            scope: api
            configFile: 'tst.json'
            secrets: '${{ toJson(secrets) }}'
      - name: Step 1
        run: |
          echo "State is: '${{ env.Storage_Path }}'"