name: use my action
on: push
jobs:
  tst:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: jnus/json-variables@v1
      - uses: ./action.yml
        with:
          scope: Dev
          configFile: 'tst.json'
          secrets: '${{ toJson(secrets) }}'

