name: test
on: push
jobs:
    steps:
      - name: Set environment specific variables
        uses: jnus/json-variables@4a442c701d13455259c65b315c7dce51d1c9edf7
        with:
            scope: Dev
            configFile: 'variables.minimal.json'
            secrets: '${{ toJson(secrets) }}'